spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/v1/book/**
        - id: library-service
          uri: lb://library-service
          predicates:
            - Path=/v1/library/**

server:
  port: 8888

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: info
